spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project-subjectcontest?serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    port: 6379
#    host: localhost
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8888

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


files:
  upload:
    path: D:\temp\files\


ip: localhost
